### ISSUE TITLE
sawyer, boost 1.69, and tribool explicit conversion

### ISSUE THREAD

**Issue by mwkrentel** [matzke1/sawyer#4]
Hi, have you tried building sawyer with the latest boost 1.69?
I think you'll find that the build fails.

I don't use Sawyer directly.  But I do use Dyninst which imports code
from Rose which uses Sawyer.  The comments in the sawyer files say to
report changes back here, so ....

Starting with boost 1.69, boost::logic::tribool changed the conversion
operator for tribool to bool to add 'explicit'.  This breaks the
sawyer build in two places.

Message.h, using tribool 'bold' in ColorSpec.

```
  380     /** Returns true if this object is in its default-constructed state. */
  381     bool isDefault() const { return COLOR_DEFAULT==foreground && COLOR_DEFAULT==background && !bold; }
```

and in Message.C, using 'isBuffered' from MesgProps.

```
 1107      for (BakedDestinations::const_iterator bi=baked_->begin(); bi!=baked_->end() && !anyUnbuffered_; ++bi)
 1108          anyUnbuffered_ = !bi->second.isBuffered;
```

There's an easy fix/workaround.  Just add an explicit static_cast in
both places.  Alternatively, you could build with
-DBOOST_NO_CXX11_EXPLICIT_CONVERSION_OPERATORS, but the cast is more
robust.

I added a PR to dyninst for this in dyninst/dyninst #541
and to spack in spack/spack #10454.

Just fyi ...

**Comment by matzke1** [comment]
Thanks for the report. I haven't tried boost 1.69, but will do so. I'm also a ROSE developer, so the Sawyer changes will make their way into ROSE automatically.

**Comment by matzke1** [comment]
I believe the compile errors are fixed in Sawyer now (this repo) with regard to Boost-1.69.0. It will take a few days for these to filter into the ROSE development repo at https://github.com/rose-compiler/rose-develop.
